decrypt:
  settings.xml: "repo/.rultor/settings.xml.asc"
  pubring.gpg: "repo/.rultor/pubring.gpg.asc"
  secring.gpg: "repo/.rultor/secring.gpg.asc"

merge:
  script:
    - mvn install -B -T10

release:
  script:
    - mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=${tag}
    - git commit -am "Release ${tag}"
    - git tag -a ${tag} -m "version ${tag}"
    - mvn clean install -Psonatype-oss-release --settings /home/r/settings.xml -Dgpg.homedir=/home/r/
    - mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=${next}
    - git commit -am "Next development version ${next}"
    - git push origin master
    - git push origin --tags
    - git checkout gh-pages
    - mkdir -p p2/${tag}
    - cp m2e-configurator/com.marvinformatics.formatter.site/target/repository/* p2/${tag}
    - git add p2/${tag}
    - git commit -am "Release ${tag}"
    - git push origin gh-pages
	
