language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
install: echo "Skipping pre-fetch of maven dependencies"
before_script: mvn validate formatter:validate
script: mvn clean verify
after_success: mvn resources:resources jacoco:merge jacoco:report coveralls:report -Pcoveralls
