language: java
sudo: false

jdk:
  - oraclejdk8

before_script:
  - ./mvnw validate formatter:validate

after_success:
  - ./mvnw resources:resources jacoco:merge jacoco:report coveralls:report -DrepoToken=OL0MbvrGAzu589jSHioduc5jAOhDxqwGe -Pcoveralls -N -B
