language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
# skip pre-fetch of maven dependencies by making install step a NOOP
install: true
before_script: mvn validate formatter:validate
script: mvn clean verify
after_success: mvn resources:resources jacoco:merge jacoco:report coveralls:report -Pcoveralls
